[tool.poetry]
name = "graph-ping"
version = "0.1.0"
description = ""
authors = ["Earl Hikky <earlhikky91@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
matplotlib = "^3.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
